services:
  - type: web
    name: dp-wizard-enhanced
    env: python
    plan: free
    buildCommand: pip install -e ".[app]"
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

